<template lang="pug" src="./Courses.pug"></template>

<script>
import jsonCourses from './Courses.json'

export default {
  name: 'Courses',
  data () {
    return {
      sectionTitle: 'Verdiğim Eğitimler',
      courses: jsonCourses,
      isActiveTab: 'allCompanies',
      isActiveFilter: 'allCourses'
    }
  },
  methods: {
    showAllCompanies () {
      this.courses[0].isCompanyVisible = true //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = true //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = true //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = true //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = true //  [SSI] open water diver
      this.courses[5].isCompanyVisible = true //  [SSI] dive guide
      this.courses[6].isCompanyVisible = true //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = true //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = true //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = true //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = true // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = true // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = true // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = true // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = true // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = true // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = true // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = true // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = true // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = true // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = true // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = true // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = true // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = true // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = true // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = true // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = true // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = true // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = true // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = true // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = true // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = true // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = true // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = true // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = true // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = true // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = true // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = true // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = true // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = true // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = true // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = true // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = true // [SSI] Advanced Adventurer
      this.isActiveTab = 'allCompanies'
      this.isActiveFilter = 'allCourses'
    },
    showGue () {
      this.courses[0].isCompanyVisible = true //   [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveTab = 'gue'
      this.isActiveFilter = 'allCourses'
    },
    showTssf () {
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = true //   [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = true //   [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = true //   [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = true //   [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = true //   [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = true //   [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = true //  [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = true //  [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = true //  [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = true //  [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = true //  [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = true //  [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = true //  [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = true //  [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = true //  [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = true //  [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = true //  [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = true //  [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = true //  [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = true //  [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = true //  [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = true //  [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = true //  [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = true //  [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = true //  [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveTab = 'tssf'
      this.isActiveFilter = 'allCourses'
    },
    showSsi () {
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = true //   [SSI] open water diver
      this.courses[5].isCompanyVisible = true //   [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = true //  [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = true //  [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = true //  [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = true //  [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = true //  [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = true //  [SSI] Try Scuba
      this.courses[41].isCompanyVisible = true //  [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = true //  [SSI] Advanced Adventurer
      this.isActiveTab = 'ssi'
      this.isActiveFilter = 'allCourses'
    },
    showProTec () {
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici <------
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici <------
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici <------
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi <------
      this.courses[10].isCompanyVisible = true //  [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = true //  [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = true //  [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = true //  [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi <------
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = true //  [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi <------
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi <------
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveTab = 'protec'
      this.isActiveFilter = 'allCourses'
    },
    showBeginner () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = true //   [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = true //   [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = true //  [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = true // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveFilter = 'beginner'
    },
    showAdvanced () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = true //   [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = true //   [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = true //   [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = true //   [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = true //  [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = true //  [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveFilter = 'diver'
    },
    showSpecialty () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = true //   [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = true //   [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = true //   [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = true //  [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = true //  [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = true //  [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = true //  [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = true //  [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = true //  [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = true //  [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = true //  [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = true //  [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = true //  [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = true //  [SSI] marine-ecology
      this.courses[21].isCompanyVisible = true //  [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = true //  [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = true //  [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = true //  [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = true //  [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = true //  [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = true //  [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = true //  [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = true //  [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = true //  [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = true //  [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = true // [SSI] Advanced Adventurer
      this.isActiveFilter = 'specialty'
    },
    showDisabled () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = true //  [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = true //  [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = true //  [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = true //  [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveFilter = 'disabled'
    },
    showFree () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = false //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = false // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = true //  [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = true //  [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = false // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveFilter = 'free'
    },
    showSpecialProgram () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = false //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = false //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = false //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = false //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = false //  [SSI] open water diver
      this.courses[5].isCompanyVisible = false //  [SSI] dive guide
      this.courses[6].isCompanyVisible = true //   [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = false //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = false //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = false //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = false // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = false // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = false // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = false // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = false // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = false // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = false // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = false // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = false // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = false // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = false // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = false // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = false // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = false // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = false // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = false // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = false // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = false // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = false // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = false // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = false // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = false // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = true //  [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = false // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = false // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = false // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = false // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = false // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = false // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = false // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = false // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = true //  [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = false // [SSI] Advanced Adventurer
      this.isActiveFilter = 'special'
    },
    showAllCourses () {
      this.showAllCompanies()
      this.courses[0].isCompanyVisible = true //  [GUE] Fundamentals
      this.courses[1].isCompanyVisible = true //  [TSSF / ProTec] 1 yildiz dalici
      this.courses[2].isCompanyVisible = true //  [TSSF / ProTec] 2 yildiz dalici
      this.courses[3].isCompanyVisible = true //  [TSSF / ProTec] 3 yildiz dalici
      this.courses[4].isCompanyVisible = true //  [SSI] open water diver
      this.courses[5].isCompanyVisible = true //  [SSI] dive guide
      this.courses[6].isCompanyVisible = true //  [NEV] modifiye dalici
      this.courses[7].isCompanyVisible = true //  [TSSF] akinti-dalisi-uzmanligi
      this.courses[8].isCompanyVisible = true //  [TSSF] arama-ve-kurtarma-uzmanligi
      this.courses[9].isCompanyVisible = true //  [TSSF / ProTec] batik-dalisi-uzmanligi
      this.courses[10].isCompanyVisible = true // [ProTec] buz-dalisi-uzmanligi
      this.courses[11].isCompanyVisible = true // [TSSF] derin-dalis-uzmanligi
      this.courses[12].isCompanyVisible = true // [ProTec] dpv-uzmanligi
      this.courses[13].isCompanyVisible = true // [TSSF] gece-dalisi-uzmanligi
      this.courses[14].isCompanyVisible = true // [TSSF] ilkyardim-uzmanligi
      this.courses[15].isCompanyVisible = true // [TSSF] irtifa-dalisi-uzmanligi
      this.courses[16].isCompanyVisible = true // [TSSF] kovuk-dalisi-uzmanligi
      this.courses[17].isCompanyVisible = true // [ProTec] kuru-elbise-uzmanligi
      this.courses[18].isCompanyVisible = true // [ProTec] magara-kesif-dalisi-uzmanligi
      this.courses[19].isCompanyVisible = true // [TSSF] malzeme-bakimi-uzmanligi
      this.courses[20].isCompanyVisible = true // [SSI] marine-ecology
      this.courses[21].isCompanyVisible = true // [TSSF / ProTec] nitrox-uzmanligi
      this.courses[22].isCompanyVisible = true // [TSSF] oksijen-kullanimi-uzmanligi
      this.courses[23].isCompanyVisible = true // [ProTec] sidemount-uzmanligi
      this.courses[24].isCompanyVisible = true // [SSI] Stress & Rescue
      this.courses[25].isCompanyVisible = true // [TSSF] sualti-fotografcisi-uzmanligi
      this.courses[26].isCompanyVisible = true // [TSSF] sualti-kultur-mirasinin-korunması-uzmanligi
      this.courses[27].isCompanyVisible = true // [TSSF] sualti-videocusu-uzmanligi
      this.courses[28].isCompanyVisible = true // [TSSF] tanitim-dalisi-uzmanligi
      this.courses[29].isCompanyVisible = true // [TSSF] tup-doldurma-uzmanligi
      this.courses[30].isCompanyVisible = true // [TSSF / SSI] ust-duzey-yuzerlilik-uzmanligi
      this.courses[31].isCompanyVisible = true // [TSSF] yon-bulma-uzmanligi
      this.courses[32].isCompanyVisible = true // [NEV] zero to hero egitimi
      this.courses[33].isCompanyVisible = true // [SSI] Snorkel Diver
      this.courses[34].isCompanyVisible = true // [ProTec] serbest dalis egitimi
      this.courses[35].isCompanyVisible = true // [TSSF / ProTec] engelli dalici 1 egitimi
      this.courses[36].isCompanyVisible = true // [TSSF] engelli dalici 2 egitimi
      this.courses[37].isCompanyVisible = true // [TSSF] engelli dalici 3 egitimi
      this.courses[38].isCompanyVisible = true // [TSSF] engelli dalici egitmen asistani
      this.courses[39].isCompanyVisible = true // [SSI] Scuba Ranger
      this.courses[40].isCompanyVisible = true // [SSI] Try Scuba
      this.courses[41].isCompanyVisible = true // [SSI] Scuba Skills Update
      this.courses[42].isCompanyVisible = true // [SSI] Advanced Adventurer
      this.isActiveFilter = 'allCourses'
    }
  }
}
</script>

<style lang="sass" src="./Courses.sass" scoped></style>
